# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-24 08:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Group leader',
                'verbose_name_plural': 'Group leaders',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='enter your name here', max_length=30, verbose_name='* Name')),
                ('middle_name', models.CharField(blank=True, default='', help_text='enter your middle name here', max_length=50, verbose_name='Middle name')),
                ('last_name', models.CharField(blank=True, default='', help_text='enter your last name here', max_length=50, verbose_name='Last name')),
                ('bdate', models.DateField(blank=True, help_text='pick your birthday', null=True, verbose_name='Birthday')),
                ('stud_id', models.CharField(blank=True, default='', help_text='enter your student id number', max_length=16, unique=True, verbose_name='Student id')),
                ('user', models.OneToOneField(blank=True, help_text='point appropriate user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter group name here', max_length=50, unique=True, verbose_name='* Name')),
            ],
            options={
                'verbose_name': 'Group of students',
                'verbose_name_plural': 'Student groups',
            },
        ),
        migrations.CreateModel(
            name='StudentGroupDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(help_text='pick a group to assign a student for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.StudentGroup', verbose_name='* Group')),
                ('student', models.ForeignKey(help_text='pick a student', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Student', verbose_name='* Student')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.AddField(
            model_name='grouplead',
            name='group',
            field=models.ForeignKey(help_text='pick a group to assign a leader for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.StudentGroup', verbose_name='* Group'),
        ),
        migrations.AddField(
            model_name='grouplead',
            name='leader',
            field=models.ForeignKey(help_text='pick a leader from a students', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Student', verbose_name='* Leader'),
        ),
    ]
